"""Per-trade configuration: services, colors, taglines, testimonials, copy pools."""

TRADE_CONFIG = {
    "hvac": {
        "display_name": "HVAC",
        "icon": "\u2744\ufe0f",
        "primary_color": "from-blue-600",
        "secondary_color": "to-cyan-500",
        "accent_color": "blue-600",
        "hex_primary": "#2563eb",
        "hex_dark": "#1d4ed8",
        "hex_light": "#eff6ff",
        "taglines": [
            "Comfort You Can Count On",
            "Keeping Your Home the Perfect Temperature",
            "Cool Summers. Warm Winters. Always.",
            "Your Comfort Is Our Business",
            "The Team That Keeps You Comfortable",
            "Because Every Home Deserves Perfect Air",
        ],
        "subtitles": [
            "Serving homeowners and businesses across {city}",
            "Fast, reliable heating and cooling for {city} families",
            "{city}'s trusted name in home comfort",
            "Licensed, insured & ready to serve {city}",
            "From emergency repairs to full installs — proudly serving {city}",
            "Keeping {city} comfortable since day one",
        ],
        "about_paragraphs": [
            {
                "p1": "{company_name} is the team {city} homeowners call when comfort matters. We handle everything from emergency AC breakdowns to full furnace replacements — and we do it right the first time.",
                "p2": "Our licensed technicians arrive on time, explain your options honestly, and never push services you don't need. That's the kind of {trade} company we'd want to call ourselves.",
            },
            {
                "p1": "When your heating or cooling system fails, you need a team that shows up fast and fixes it right. {company_name} has built its reputation in {city} on exactly that — prompt service and honest work.",
                "p2": "We're fully licensed, insured, and committed to fair pricing. Whether it's a tune-up or a complete system install, we treat your home like our own.",
            },
            {
                "p1": "{company_name} provides full-service {trade} for homes and businesses throughout {city}. We specialize in keeping your indoor environment comfortable and energy-efficient all year round.",
                "p2": "From routine maintenance to complex installations, our experienced crew handles it all. We stand behind every job with a satisfaction guarantee.",
            },
            {
                "p1": "Nobody plans for a broken furnace in January or a dead AC in July. That's why {company_name} offers fast, dependable {trade} service to {city} and the surrounding area.",
                "p2": "We're a locally owned company that believes in doing the job right — with quality parts, transparent pricing, and technicians who actually care about your comfort.",
            },
        ],
        "services": [
            "AC Installation & Replacement",
            "Furnace Repair & Maintenance",
            "Heat Pump Services",
            "Ductwork Installation & Repair",
            "Thermostat Installation",
            "Indoor Air Quality Solutions",
            "Emergency HVAC Repair",
            "Seasonal Tune-Ups",
            "Commercial HVAC Services",
            "Ventilation System Design",
        ],
        "testimonials": [
            {"name": "Mark T.", "stars": 5, "text": "Called them on the hottest day of summer and they had my AC running again within hours. Incredible service!"},
            {"name": "Sarah L.", "stars": 5, "text": "Very professional team. They explained everything clearly and didn't try to upsell me on things I didn't need."},
            {"name": "David R.", "stars": 5, "text": "Our furnace died in January and they came out same day. Fair pricing and quality work. Highly recommend!"},
            {"name": "Jennifer K.", "stars": 4, "text": "Great annual maintenance service. Our system runs more efficiently now and our energy bills dropped noticeably."},
            {"name": "Robert M.", "stars": 5, "text": "Installed a new heat pump for us. The crew was clean, punctual, and the install was flawless."},
            {"name": "Lisa W.", "stars": 5, "text": "Best HVAC company in the area. They've serviced our home for three years and never disappoint."},
        ],
    },
    "plumbing": {
        "display_name": "Plumbing",
        "icon": "\U0001f6bf",
        "primary_color": "from-sky-600",
        "secondary_color": "to-blue-400",
        "accent_color": "sky-600",
        "hex_primary": "#0284c7",
        "hex_dark": "#0369a1",
        "hex_light": "#f0f9ff",
        "taglines": [
            "Plumbing Done Right the First Time",
            "Stop the Drip. Fix the Problem.",
            "The Plumber You'll Actually Recommend",
            "Fast Fixes. Fair Prices. Real Results.",
            "When Water's the Problem, We're the Answer",
            "Pipes, Drains & Peace of Mind",
        ],
        "subtitles": [
            "Emergency and scheduled plumbing for {city} homes",
            "Serving {city} with honest, reliable plumbing",
            "{city}'s go-to team for drains, pipes & water heaters",
            "Licensed master plumbers proudly serving {city}",
            "From leaks to full remodels — trusted in {city}",
            "Fast response plumbing across {city} and beyond",
        ],
        "about_paragraphs": [
            {
                "p1": "{company_name} has earned the trust of {city} homeowners by doing plumbing the right way — showing up on time, diagnosing the real problem, and fixing it for good.",
                "p2": "We handle everything from clogged drains and leaky faucets to water heater installs and full bathroom remodels. Licensed, insured, and always upfront about pricing.",
            },
            {
                "p1": "Plumbing emergencies don't wait, and neither does {company_name}. We offer fast-response service across {city} for everything from burst pipes to backed-up drains.",
                "p2": "Our team believes in honest diagnostics and fair quotes. We'll tell you what's wrong, what it costs, and get it done right — no surprises.",
            },
            {
                "p1": "{company_name} provides comprehensive {trade} services for residential and commercial properties throughout {city}. No job is too small, and no problem is too complex.",
                "p2": "We're the team your neighbors recommend. With experienced, licensed plumbers and a commitment to clean, quality work, we make plumbing problems disappear.",
            },
            {
                "p1": "When something goes wrong with your plumbing, you need someone you can trust in your home. {company_name} has been that company for families across {city}.",
                "p2": "We take pride in our work, stand behind every repair, and treat your property with respect. That's why our customers keep calling us back.",
            },
        ],
        "services": [
            "Drain Cleaning & Unclogging",
            "Water Heater Installation & Repair",
            "Pipe Repair & Replacement",
            "Sewer Line Services",
            "Fixture Installation",
            "Leak Detection & Repair",
            "Garbage Disposal Services",
            "Emergency Plumbing",
            "Water Softener Installation",
            "Bathroom & Kitchen Remodel Plumbing",
        ],
        "testimonials": [
            {"name": "Chris B.", "stars": 5, "text": "Fixed a major leak under our kitchen sink in no time. Very knowledgeable and left everything spotless."},
            {"name": "Amanda S.", "stars": 5, "text": "They replaced our old water heater and the difference is amazing. Hot water on demand now!"},
            {"name": "Tom H.", "stars": 5, "text": "Had a clogged drain that two other companies couldn't fix. These guys solved it on the first visit."},
            {"name": "Rachel P.", "stars": 4, "text": "Professional, on time, and reasonably priced. They're now our go-to plumber for everything."},
            {"name": "Steve G.", "stars": 5, "text": "Emergency call at 11pm and they were at our door within 30 minutes. Saved us from a flooded basement."},
            {"name": "Nicole D.", "stars": 5, "text": "Honest and dependable. They gave us options and helped us choose what fit our budget."},
        ],
    },
    "electrical": {
        "display_name": "Electrical",
        "icon": "\u26a1",
        "primary_color": "from-amber-500",
        "secondary_color": "to-yellow-400",
        "accent_color": "amber-500",
        "hex_primary": "#f59e0b",
        "hex_dark": "#d97706",
        "hex_light": "#fffbeb",
        "taglines": [
            "Safe Wiring. Bright Results.",
            "Power Your Home with Confidence",
            "Electrical Work You Can Trust",
            "The Spark Behind Every Safe Home",
            "Wired for Quality",
            "Lighting Up Homes the Right Way",
        ],
        "subtitles": [
            "Licensed electricians serving {city} homes and businesses",
            "From panel upgrades to full rewires — trusted in {city}",
            "{city}'s choice for safe, code-compliant electrical work",
            "Fast, reliable electrical service across {city}",
            "Expert wiring, lighting & electrical repair in {city}",
            "Keeping {city} homes powered and protected",
        ],
        "about_paragraphs": [
            {
                "p1": "{company_name} is the electrician {city} homeowners trust for safe, code-compliant work. From outlet installs to whole-home rewiring, we do it all with precision.",
                "p2": "Our licensed team takes safety seriously and never cuts corners. We explain what we're doing, why it matters, and leave your home safer than we found it.",
            },
            {
                "p1": "Electrical problems are no place for guesswork. {company_name} brings experienced, licensed electricians to every job in {city} — big or small.",
                "p2": "Whether you need a panel upgrade, EV charger installation, or troubleshooting a tricky circuit, we get it done right, up to code, and on budget.",
            },
            {
                "p1": "{company_name} provides full-service {trade} work for homes and businesses throughout {city}. We specialize in making your electrical systems safe, efficient, and up to date.",
                "p2": "Our customers come back because we do quality work at fair prices. Every job gets the same attention to detail, whether it's installing a ceiling fan or rewiring a kitchen.",
            },
            {
                "p1": "Your home's electrical system is too important for shortcuts. {company_name} has built a reputation in {city} for thorough, professional electrical work that passes inspection every time.",
                "p2": "We're fully licensed, insured, and committed to your safety. Call us for honest assessments, transparent pricing, and work you can count on for years.",
            },
        ],
        "services": [
            "Electrical Panel Upgrades",
            "Outlet & Switch Installation",
            "Lighting Installation & Design",
            "Ceiling Fan Installation",
            "Whole-Home Rewiring",
            "EV Charger Installation",
            "Generator Installation",
            "Smoke & CO Detector Installation",
            "Surge Protection",
            "Commercial Electrical Services",
        ],
        "testimonials": [
            {"name": "Brian F.", "stars": 5, "text": "Upgraded our entire panel to handle modern loads. Work was clean and passed inspection with flying colors."},
            {"name": "Karen J.", "stars": 5, "text": "Installed recessed lighting throughout our home. It looks absolutely amazing and was done in one day."},
            {"name": "Mike C.", "stars": 5, "text": "Very safety-conscious team. They found and fixed wiring issues the previous owners left behind."},
            {"name": "Donna A.", "stars": 4, "text": "Quick and professional EV charger installation. Now we charge at home every night hassle-free."},
            {"name": "Greg W.", "stars": 5, "text": "They rewired our 1960s home and brought everything up to code. Couldn't be happier with the results."},
            {"name": "Patricia N.", "stars": 5, "text": "Always responsive and fair with pricing. We've used them for multiple projects now."},
        ],
    },
    "lawn care": {
        "display_name": "Lawn Care",
        "icon": "\U0001f33f",
        "primary_color": "from-green-600",
        "secondary_color": "to-lime-500",
        "accent_color": "green-600",
        "hex_primary": "#16a34a",
        "hex_dark": "#15803d",
        "hex_light": "#f0fdf4",
        "taglines": [
            "Your Yard, Perfected",
            "The Lawn Your Neighbors Will Envy",
            "Thick, Green & Hassle-Free",
            "Great Lawns Don't Happen by Accident",
            "Curb Appeal Starts with the Grass",
            "A Better Lawn Starts Here",
        ],
        "subtitles": [
            "Professional lawn maintenance for {city} homeowners",
            "Mowing, fertilizing & weed control across {city}",
            "{city}'s trusted team for lush, healthy lawns",
            "Keeping {city} yards looking their best, year-round",
            "Affordable lawn programs tailored for {city} homes",
            "Your local lawn care experts in {city}",
        ],
        "about_paragraphs": [
            {
                "p1": "{company_name} takes the work out of having a beautiful lawn. We provide reliable, professional {trade} across {city} — so you can enjoy your yard instead of working in it.",
                "p2": "From weekly mowing to seasonal fertilization programs, we tailor our services to your lawn's specific needs. Consistent results, fair pricing, and a yard you'll be proud of.",
            },
            {
                "p1": "A great lawn doesn't happen by accident — it takes the right care at the right time. {company_name} brings that expertise to {city} homeowners week after week.",
                "p2": "We're locally owned, fully insured, and committed to making your lawn the healthiest on the block. No contracts required — just great results that keep you coming back.",
            },
            {
                "p1": "{company_name} offers comprehensive {trade} services throughout {city}. We handle the mowing, edging, fertilizing, and weed control so you don't have to.",
                "p2": "Our team shows up on schedule, does thorough work, and leaves your property looking clean and sharp. It's lawn care you can count on, season after season.",
            },
            {
                "p1": "Your lawn says a lot about your home. {company_name} makes sure it says the right things — with consistent, professional {trade} designed for {city}'s climate and soil.",
                "p2": "We customize every plan to your yard's unique conditions. Whether you need basic maintenance or a full lawn restoration, we'll get you the results you want.",
            },
        ],
        "services": [
            "Weekly Lawn Mowing",
            "Lawn Fertilization Programs",
            "Weed Control & Treatment",
            "Aeration & Overseeding",
            "Spring & Fall Cleanup",
            "Edging & Trimming",
            "Sod Installation",
            "Lawn Disease Treatment",
            "Irrigation System Maintenance",
            "Organic Lawn Care",
        ],
        "testimonials": [
            {"name": "Paul E.", "stars": 5, "text": "My lawn has never looked this good. The neighbors keep asking who my lawn guy is!"},
            {"name": "Susan M.", "stars": 5, "text": "Reliable, consistent, and my yard looks like a golf course. Best decision I've made for my home."},
            {"name": "Dan K.", "stars": 5, "text": "They revived my brown, patchy lawn into something beautiful. Great fertilization program."},
            {"name": "Mary L.", "stars": 4, "text": "Always on time and do a thorough job. They even blow off the driveway and sidewalks after mowing."},
            {"name": "Jeff R.", "stars": 5, "text": "The aeration and overseeding service made a huge difference. Thick, green lawn all season long."},
            {"name": "Cindy T.", "stars": 5, "text": "Affordable and professional. They customized a plan for my yard's specific needs."},
        ],
    },
    "landscaping": {
        "display_name": "Landscaping",
        "icon": "\U0001f333",
        "primary_color": "from-emerald-600",
        "secondary_color": "to-green-400",
        "accent_color": "emerald-600",
        "hex_primary": "#059669",
        "hex_dark": "#047857",
        "hex_light": "#ecfdf5",
        "taglines": [
            "Outdoor Spaces Worth Living In",
            "Designed for How You Actually Live",
            "Where Vision Meets the Landscape",
            "Your Property's Full Potential, Realized",
            "Transform Your Outdoors",
            "Landscapes That Last a Lifetime",
        ],
        "subtitles": [
            "Custom landscape design and installation in {city}",
            "Hardscaping, planting & outdoor living for {city} homes",
            "{city}'s trusted team for stunning outdoor transformations",
            "From concept to completion — landscaping in {city}",
            "Creating beautiful, functional outdoor spaces in {city}",
            "Serving {city} with thoughtful, lasting landscape design",
        ],
        "about_paragraphs": [
            {
                "p1": "{company_name} creates outdoor spaces that are as functional as they are beautiful. We serve {city} homeowners with custom landscape design, hardscaping, and planting that stands the test of time.",
                "p2": "From initial concept to final walkthrough, our team handles every detail. We listen to your vision, work within your budget, and deliver results that transform how you use your property.",
            },
            {
                "p1": "Great {trade} is about more than plants — it's about creating an outdoor space that fits your life. {company_name} brings that philosophy to every project in {city}.",
                "p2": "Whether it's a patio, a retaining wall, or a complete yard overhaul, we use quality materials and proven techniques to build landscapes that look better with every passing year.",
            },
            {
                "p1": "{company_name} offers full-service {trade} for residential and commercial properties throughout {city}. We design, build, and maintain outdoor spaces that our clients love.",
                "p2": "Our crew takes pride in clean craftsmanship, attention to detail, and projects that finish on time and on budget. Your satisfaction is our best advertising.",
            },
            {
                "p1": "Your outdoor space should be your favorite part of your property. {company_name} makes that happen for homeowners across {city} with thoughtful design and quality installation.",
                "p2": "We specialize in creating low-maintenance, high-impact landscapes tailored to the local climate. Let us show you what's possible.",
            },
        ],
        "services": [
            "Landscape Design & Planning",
            "Hardscape Installation",
            "Patio & Walkway Construction",
            "Retaining Wall Building",
            "Garden Bed Installation",
            "Outdoor Lighting",
            "Water Feature Installation",
            "Xeriscaping & Drought-Tolerant Design",
            "Mulch & Rock Installation",
            "Seasonal Planting",
        ],
        "testimonials": [
            {"name": "Andrew B.", "stars": 5, "text": "They transformed our backyard into an oasis. The patio and garden design exceeded our expectations."},
            {"name": "Michelle G.", "stars": 5, "text": "Creative designers who really listen. Our front yard went from embarrassing to the best on the block."},
            {"name": "Kevin D.", "stars": 5, "text": "The retaining wall they built is both functional and beautiful. Great craftsmanship throughout."},
            {"name": "Laura S.", "stars": 4, "text": "Excellent xeriscaping work that cut our water bill in half. Looks gorgeous year-round."},
            {"name": "Ryan P.", "stars": 5, "text": "Professional crew, on budget, and finished ahead of schedule. Our outdoor space is now our favorite room."},
            {"name": "Heather W.", "stars": 5, "text": "From design to final install, everything was seamless. We get compliments from everyone who visits."},
        ],
    },
    "roofing": {
        "display_name": "Roofing",
        "icon": "\U0001f3e0",
        "primary_color": "from-red-700",
        "secondary_color": "to-orange-500",
        "accent_color": "red-700",
        "hex_primary": "#b91c1c",
        "hex_dark": "#991b1b",
        "hex_light": "#fef2f2",
        "taglines": [
            "A Roof You Can Count On",
            "Protection Starts at the Top",
            "Built to Weather Any Storm",
            "Strong Roofs. Honest Work.",
            "The Last Roofer You'll Ever Need",
            "Keeping What Matters Safe & Dry",
        ],
        "subtitles": [
            "Roof repair, replacement & storm damage in {city}",
            "Trusted roofing contractors serving {city} since day one",
            "{city}'s choice for quality roofing at fair prices",
            "Expert shingle, metal & flat roof work in {city}",
            "From inspections to full replacements — serving {city}",
            "Licensed, insured roofing professionals in {city}",
        ],
        "about_paragraphs": [
            {
                "p1": "{company_name} protects {city} homes from the top down. We specialize in roof repairs, replacements, and storm damage restoration — done right, with materials built to last.",
                "p2": "Our team provides honest inspections, transparent estimates, and clean, professional installations. We'll never recommend work you don't need, and we stand behind everything we do.",
            },
            {
                "p1": "Your roof is your home's first line of defense. {company_name} makes sure it's a strong one — with expert {trade} services trusted by homeowners across {city}.",
                "p2": "Whether it's a few missing shingles or a complete tear-off, we bring the same level of care and craftsmanship to every project. Quality materials, skilled crews, guaranteed results.",
            },
            {
                "p1": "{company_name} has built its name in {city} by doing {trade} the right way — thorough inspections, fair quotes, and installations that hold up for decades.",
                "p2": "We work with all roof types and handle insurance claims with ease. Our customers trust us because we deliver on what we promise, every single time.",
            },
            {
                "p1": "Storm damage? Aging shingles? A nagging leak? {company_name} handles it all for {city} homeowners with fast, professional {trade} services you can rely on.",
                "p2": "We're a locally owned company that believes in honest work and fair prices. From the first phone call to the final cleanup, we make the process easy.",
            },
        ],
        "services": [
            "Roof Replacement",
            "Roof Repair & Patching",
            "Shingle Installation",
            "Metal Roofing",
            "Flat Roof Services",
            "Roof Inspection & Assessment",
            "Storm Damage Repair",
            "Gutter Installation & Repair",
            "Skylight Installation",
            "Commercial Roofing",
        ],
        "testimonials": [
            {"name": "James H.", "stars": 5, "text": "Replaced our entire roof in two days. Clean, efficient, and the new roof looks fantastic."},
            {"name": "Barbara C.", "stars": 5, "text": "They found and fixed a leak that had been causing damage for months. Thorough and professional."},
            {"name": "William F.", "stars": 5, "text": "Handled our insurance claim for storm damage seamlessly. Made a stressful situation easy."},
            {"name": "Linda M.", "stars": 4, "text": "Great quality materials and workmanship. Our metal roof should last a lifetime."},
            {"name": "Charles R.", "stars": 5, "text": "Fair estimate, no surprises, and excellent cleanup. You'd never know they were here except for the beautiful new roof."},
            {"name": "Elizabeth A.", "stars": 5, "text": "The best roofing company we've ever worked with. Responsive, honest, and skilled."},
        ],
    },
    "painting": {
        "display_name": "Painting",
        "icon": "\U0001f3a8",
        "primary_color": "from-violet-600",
        "secondary_color": "to-purple-400",
        "accent_color": "violet-600",
        "hex_primary": "#7c3aed",
        "hex_dark": "#6d28d9",
        "hex_light": "#f5f3ff",
        "taglines": [
            "A Fresh Coat Changes Everything",
            "Color That Makes Your Home Come Alive",
            "Walls Worth Showing Off",
            "Where Precision Meets Personality",
            "The Finish You've Been Looking For",
            "Transforming Spaces, One Room at a Time",
        ],
        "subtitles": [
            "Interior, exterior & specialty finishes in {city}",
            "Serving homeowners and businesses across {city}",
            "{city}'s choice for lasting, beautiful paint jobs",
            "Trusted by hundreds of families in {city}",
            "From accent walls to full exteriors — proudly serving {city}",
            "Licensed, insured & local to {city}",
        ],
        "about_paragraphs": [
            {
                "p1": "{company_name} brings meticulous craftsmanship to every {trade} project in {city}. We prep surfaces the right way, use premium paints, and leave sharp, clean lines that last.",
                "p2": "Whether it's refreshing a single room or transforming your entire exterior, our team treats your property with the same care we'd give our own homes.",
            },
            {
                "p1": "A great paint job isn't just about color — it's about preparation, technique, and attention to detail. {company_name} delivers all three to {city} homeowners.",
                "p2": "We offer free color consultations, use top-quality materials, and always finish on schedule. Our goal is simple: results that make you love your space again.",
            },
            {
                "p1": "{company_name} provides professional {trade} services for homes and businesses throughout {city}. From interior refreshes to full exterior transformations, we do it all.",
                "p2": "Our experienced crew is known for clean work, proper prep, and finishes that stand the test of time. We protect your furniture, your floors, and your investment.",
            },
            {
                "p1": "Ready for a change? {company_name} makes it easy with professional {trade} services across {city}. We handle everything from drywall prep to the final brushstroke.",
                "p2": "We're the painters your neighbors recommended. Affordable, reliable, and committed to a finish that looks beautiful for years to come.",
            },
        ],
        "services": [
            "Interior Painting",
            "Exterior Painting",
            "Cabinet Painting & Refinishing",
            "Deck & Fence Staining",
            "Drywall Repair & Texturing",
            "Color Consultation",
            "Wallpaper Removal",
            "Pressure Washing",
            "Commercial Painting",
            "Epoxy Floor Coating",
        ],
        "testimonials": [
            {"name": "Scott B.", "stars": 5, "text": "Painted our entire interior in three days. Clean lines, no drips, and beautiful color matching."},
            {"name": "Angela T.", "stars": 5, "text": "The exterior paint job made our house look brand new. Neighbors think we renovated!"},
            {"name": "Jason K.", "stars": 5, "text": "Their cabinet refinishing saved us thousands over replacement. Kitchen looks completely transformed."},
            {"name": "Diane L.", "stars": 4, "text": "Great attention to detail. They properly prepped every surface and it shows in the final result."},
            {"name": "Timothy M.", "stars": 5, "text": "Professional crew that respects your home. Drop cloths everywhere, furniture moved carefully, spotless cleanup."},
            {"name": "Carolyn R.", "stars": 5, "text": "The color consultation was so helpful. They guided us to the perfect palette for our space."},
        ],
    },
    "pest control": {
        "display_name": "Pest Control",
        "icon": "\U0001f41c",
        "primary_color": "from-teal-600",
        "secondary_color": "to-green-500",
        "accent_color": "teal-600",
        "hex_primary": "#0d9488",
        "hex_dark": "#0f766e",
        "hex_light": "#f0fdfa",
        "taglines": [
            "Your Home. Pest-Free. Guaranteed.",
            "Take Back Your Space",
            "We Handle the Bugs So You Don't Have To",
            "Protection for Your Home, Inside and Out",
            "One Call. No More Pests.",
            "Safe, Effective Pest Solutions That Work",
        ],
        "subtitles": [
            "Residential and commercial pest solutions in {city}",
            "Keeping {city} homes pest-free, season after season",
            "{city}'s trusted choice for safe, effective pest control",
            "Fast response pest removal and prevention in {city}",
            "Family-safe treatments serving {city} and surrounding areas",
            "Licensed pest professionals proudly serving {city}",
        ],
        "about_paragraphs": [
            {
                "p1": "{company_name} protects {city} homes and businesses from unwanted pests. We use proven, family-safe treatments that eliminate the problem and keep it from coming back.",
                "p2": "Our licensed technicians identify the source of the issue — not just the symptoms — and build a treatment plan that works. We stand behind every service we provide.",
            },
            {
                "p1": "Pests don't belong in your home. {company_name} offers fast, effective {trade} services across {city} — from one-time treatments to ongoing prevention plans.",
                "p2": "We use modern, low-toxicity methods that are safe for your family and pets. Our goal is a pest-free home you can feel good about.",
            },
            {
                "p1": "{company_name} provides comprehensive {trade} for residential and commercial properties throughout {city}. Whatever's bugging you, we'll take care of it.",
                "p2": "Our team is fully licensed, insured, and trained in the latest treatment methods. We offer flexible scheduling, transparent pricing, and results that last.",
            },
            {
                "p1": "When pests invade, you want them gone — fast. {company_name} delivers quick, thorough {trade} to {city} homeowners with treatments that work the first time.",
                "p2": "We're a locally owned company that treats your home like our own. That means careful application, thorough follow-up, and guaranteed results.",
            },
        ],
        "services": [
            "General Pest Treatment",
            "Ant & Spider Control",
            "Rodent Removal & Exclusion",
            "Termite Inspection & Treatment",
            "Mosquito Control",
            "Wasp & Bee Removal",
            "Bed Bug Treatment",
            "Wildlife Removal",
            "Recurring Prevention Plans",
            "Commercial Pest Management",
        ],
        "testimonials": [
            {"name": "Nathan R.", "stars": 5, "text": "Got rid of our ant problem completely after one treatment. No more bugs in the kitchen!"},
            {"name": "Kelly S.", "stars": 5, "text": "Their quarterly plan keeps our home pest-free year-round. Haven't seen a spider in months."},
            {"name": "Anthony J.", "stars": 5, "text": "Professional rodent exclusion service. They sealed every entry point and the mice are gone for good."},
            {"name": "Deborah H.", "stars": 4, "text": "Thorough termite inspection and treatment. They explained everything and put our minds at ease."},
            {"name": "Frank P.", "stars": 5, "text": "Safe treatments that are effective but gentle around our kids and pets. Very impressed."},
            {"name": "Marie G.", "stars": 5, "text": "Fast response time and the technician was incredibly knowledgeable. Problem solved on the first visit."},
        ],
    },
    "carpet cleaning": {
        "display_name": "Carpet Cleaning",
        "icon": "\u2728",
        "primary_color": "from-indigo-600",
        "secondary_color": "to-blue-400",
        "accent_color": "indigo-600",
        "hex_primary": "#4f46e5",
        "hex_dark": "#4338ca",
        "hex_light": "#eef2ff",
        "taglines": [
            "Deep Clean. Fresh Start.",
            "Carpets That Look and Feel Brand New",
            "The Clean You Can See and Smell",
            "Revive Your Floors. Love Your Home.",
            "Stains Out. Freshness In.",
            "Professional Clean. Lasting Results.",
        ],
        "subtitles": [
            "Deep steam cleaning for {city} homes and businesses",
            "Carpet, upholstery & tile cleaning across {city}",
            "{city}'s trusted team for spotless, fresh carpets",
            "Pet stains, odors & tough spots — handled in {city}",
            "Move-in, move-out & routine cleaning in {city}",
            "Fast-drying, deep-cleaning service in {city}",
        ],
        "about_paragraphs": [
            {
                "p1": "{company_name} brings professional-grade {trade} to {city} homes and businesses. Our deep steam extraction removes dirt, stains, and allergens that regular vacuuming can't reach.",
                "p2": "We treat every carpet with care — pre-treating stains, protecting your furniture, and leaving your floors fresh, soft, and fast-drying. The difference is visible.",
            },
            {
                "p1": "Dirty carpets don't just look bad — they trap allergens, odors, and bacteria. {company_name} eliminates all of it with professional {trade} trusted by {city} homeowners.",
                "p2": "Our technicians use commercial-grade equipment and eco-friendly solutions to deliver a deep clean that lasts. We're thorough, reliable, and fairly priced.",
            },
            {
                "p1": "{company_name} offers full-service {trade} for homes and businesses throughout {city}. From pet stains to high-traffic areas, we restore carpets to like-new condition.",
                "p2": "We also handle upholstery, tile, and area rugs. Whatever needs cleaning, our experienced team has the tools and expertise to get it done right.",
            },
            {
                "p1": "Ready for carpets that actually look and smell clean? {company_name} provides deep, thorough {trade} across {city} — with results you'll notice immediately.",
                "p2": "We move furniture carefully, protect your baseboards, and leave everything spotless. It's the kind of service that earns repeat customers and referrals.",
            },
        ],
        "services": [
            "Deep Steam Carpet Cleaning",
            "Stain Removal Treatment",
            "Pet Odor & Stain Removal",
            "Upholstery Cleaning",
            "Tile & Grout Cleaning",
            "Area Rug Cleaning",
            "Commercial Carpet Cleaning",
            "Carpet Repair & Stretching",
            "Scotchgard Protection",
            "Move-In/Move-Out Cleaning",
        ],
        "testimonials": [
            {"name": "Travis D.", "stars": 5, "text": "Our carpets look brand new! They got out stains I thought were permanent. Amazing results."},
            {"name": "Megan F.", "stars": 5, "text": "Pet stain and odor completely gone. We can finally have guests over without embarrassment."},
            {"name": "Russell B.", "stars": 5, "text": "Used them for our move-out cleaning and got our full deposit back. Worth every penny."},
            {"name": "Amy C.", "stars": 4, "text": "Quick drying time and the carpets feel so soft and fresh. Will definitely use again."},
            {"name": "Donald W.", "stars": 5, "text": "They cleaned our upholstery too and the whole living room looks and smells incredible."},
            {"name": "Sharon J.", "stars": 5, "text": "Very professional service. They moved furniture carefully and put everything back perfectly."},
        ],
    },
    "handyman": {
        "display_name": "Handyman",
        "icon": "\U0001f527",
        "primary_color": "from-orange-600",
        "secondary_color": "to-amber-400",
        "accent_color": "orange-600",
        "hex_primary": "#ea580c",
        "hex_dark": "#c2410c",
        "hex_light": "#fff7ed",
        "taglines": [
            "One Call Fixes It All",
            "Your Home's To-Do List, Done",
            "Small Fixes. Big Difference.",
            "The Handyman Who Actually Shows Up",
            "No Job Too Small. No Excuse Not To Call.",
            "Get It Fixed. Get It Done.",
        ],
        "subtitles": [
            "Reliable home repairs and odd jobs in {city}",
            "From honey-do lists to real repairs — serving {city}",
            "{city}'s dependable handyman for any home project",
            "Fast, affordable fixes for {city} homeowners",
            "Mounting, patching, repairing & more in {city}",
            "The handyman {city} homeowners trust",
        ],
        "about_paragraphs": [
            {
                "p1": "{company_name} is the one-call solution for home repairs and odd jobs across {city}. We tackle everything from drywall patches to furniture assembly to plumbing fixes — so you don't have to.",
                "p2": "We show up on time, work efficiently, and clean up after ourselves. No job is too small, and we never charge for work we don't do.",
            },
            {
                "p1": "Every home has a list of things that need fixing. {company_name} makes that list disappear — with reliable, skilled {trade} service across {city}.",
                "p2": "Our handyman is experienced in a wide range of repairs and improvements. One visit, multiple fixes, honest pricing. It's that simple.",
            },
            {
                "p1": "{company_name} provides dependable {trade} services for {city} homeowners. We handle the repairs, installations, and improvements that keep your home running smoothly.",
                "p2": "From hanging shelves to fixing doors to caulking windows, our team does quality work at fair prices. We treat every home with care and respect.",
            },
            {
                "p1": "Tired of that leaky faucet or wobbly shelf? {company_name} fixes the things that have been on your list for months — quickly, affordably, and right here in {city}.",
                "p2": "We're the reliable, skilled handyman you've been looking for. Licensed, insured, and ready to knock out your to-do list.",
            },
        ],
        "services": [
            "General Home Repairs",
            "Furniture Assembly",
            "Drywall Patching & Repair",
            "Door & Window Repairs",
            "Shelving & Mounting",
            "Minor Plumbing Fixes",
            "Minor Electrical Work",
            "Caulking & Weatherproofing",
            "Deck & Fence Repair",
            "Honey-Do Lists",
        ],
        "testimonials": [
            {"name": "Roger K.", "stars": 5, "text": "Knocked out my entire honey-do list in one afternoon. My wife is thrilled!"},
            {"name": "Tammy L.", "stars": 5, "text": "Fixed a dozen little things around the house that had been bugging me for months. Great service."},
            {"name": "Carl M.", "stars": 5, "text": "Mounted our TV, assembled furniture, and fixed a leaky faucet all in one visit. Super efficient."},
            {"name": "Janet E.", "stars": 4, "text": "Reliable, skilled, and reasonably priced. They're my first call for any home repair now."},
            {"name": "Dennis R.", "stars": 5, "text": "Fixed drywall damage from a door handle and you can't even tell it was ever there. Impressive work."},
            {"name": "Brenda S.", "stars": 5, "text": "So nice to have one person who can handle all the little repairs. Saves time and money."},
        ],
    },
    "garage door repair": {
        "display_name": "Garage Door Repair",
        "icon": "\U0001f6aa",
        "primary_color": "from-gray-700",
        "secondary_color": "to-slate-500",
        "accent_color": "gray-700",
        "hex_primary": "#374151",
        "hex_dark": "#1f2937",
        "hex_light": "#f9fafb",
        "taglines": [
            "Doors That Open When You Need Them",
            "Stuck, Broken or Noisy? We Fix It.",
            "Your Garage Door, Working Like New",
            "Smooth, Safe & Reliable — Every Time",
            "The Fix Is Faster Than You Think",
            "Get Your Garage Back in Business",
        ],
        "subtitles": [
            "Spring, opener & panel repair across {city}",
            "Same-day garage door service in {city}",
            "{city}'s trusted garage door repair professionals",
            "Fast, affordable garage door fixes in {city}",
            "Repair, replacement & installation serving {city}",
            "Emergency and scheduled service throughout {city}",
        ],
        "about_paragraphs": [
            {
                "p1": "{company_name} gets your garage door working right — fast. We serve {city} with same-day repairs for springs, openers, panels, and tracks.",
                "p2": "Our technicians arrive prepared with the parts and tools to fix most problems on the first visit. Fair pricing, no surprises, and a door that works smoothly every time.",
            },
            {
                "p1": "A broken garage door isn't just an inconvenience — it's a security risk. {company_name} provides fast, reliable {trade} across {city} to get you back in business.",
                "p2": "From emergency spring replacements to new door installations, we handle it all. Licensed, insured, and trusted by {city} homeowners.",
            },
            {
                "p1": "{company_name} specializes in {trade} and installation for homes throughout {city}. Whether your door is off-track, noisy, or won't open, we'll diagnose and fix it.",
                "p2": "We carry parts for all major brands and back our work with a satisfaction guarantee. Our customers appreciate our honesty — we repair when we can and only recommend replacement when it makes sense.",
            },
            {
                "p1": "Garage door acting up? {company_name} has been fixing doors across {city} with fast turnarounds and honest estimates. Most repairs are done in a single visit.",
                "p2": "We also offer new garage door installations and smart opener upgrades. Whatever your garage needs, we've got you covered.",
            },
        ],
        "services": [
            "Garage Door Repair",
            "Garage Door Installation",
            "Spring Replacement",
            "Opener Repair & Installation",
            "Panel Replacement",
            "Track Alignment & Repair",
            "Weather Seal Replacement",
            "Safety Sensor Adjustment",
            "Smart Opener Upgrades",
            "Emergency Garage Door Service",
        ],
        "testimonials": [
            {"name": "Larry H.", "stars": 5, "text": "Broken spring at 7am and they had it fixed by noon. Fast, professional, and fair priced."},
            {"name": "Sandra P.", "stars": 5, "text": "Installed a beautiful new garage door that completely changed our home's curb appeal."},
            {"name": "Wayne T.", "stars": 5, "text": "Our door was off-track and they diagnosed and fixed it quickly. Runs smooth as butter now."},
            {"name": "Gloria B.", "stars": 4, "text": "Upgraded our opener to a smart one. Love being able to check if the garage is closed from my phone."},
            {"name": "Keith D.", "stars": 5, "text": "Honest assessment — they repaired what needed fixing instead of pushing a full replacement. Respect."},
            {"name": "Betty M.", "stars": 5, "text": "They service our garage doors annually. Quiet, smooth operation every time. Great preventive maintenance."},
        ],
    },
    "appliance repair": {
        "display_name": "Appliance Repair",
        "icon": "\U0001f9f0",
        "primary_color": "from-slate-600",
        "secondary_color": "to-gray-400",
        "accent_color": "slate-600",
        "hex_primary": "#475569",
        "hex_dark": "#334155",
        "hex_light": "#f8fafc",
        "taglines": [
            "Don't Replace It — We'll Fix It",
            "Fast Fixes for the Appliances You Depend On",
            "Back Up and Running Today",
            "Expert Repairs. Honest Advice.",
            "Saving Appliances (and Your Wallet)",
            "The Fix That Lasts",
        ],
        "subtitles": [
            "Refrigerator, washer, oven & more — repaired in {city}",
            "Same-day appliance diagnostics in {city}",
            "{city}'s trusted team for fast appliance repair",
            "Serving {city} with affordable, reliable appliance fixes",
            "All major brands and models serviced in {city}",
            "Experienced appliance technicians across {city}",
        ],
        "about_paragraphs": [
            {
                "p1": "{company_name} saves {city} homeowners from expensive replacements with fast, expert {trade}. If it can be fixed, we'll fix it — often on the same day you call.",
                "p2": "We work on all major brands and models: refrigerators, washers, dryers, ovens, dishwashers, and more. Honest diagnostics, fair pricing, and parts that last.",
            },
            {
                "p1": "When your appliances stop working, life gets complicated fast. {company_name} gets things running again with quick, professional {trade} across {city}.",
                "p2": "Our technicians arrive with the tools and common parts to fix most issues on the spot. If replacement makes more sense, we'll tell you honestly.",
            },
            {
                "p1": "{company_name} provides fast, dependable {trade} for homes throughout {city}. We diagnose the problem, explain your options, and get it fixed — usually in one visit.",
                "p2": "We service all major brands and stand behind our repairs. Our customers appreciate our honesty and the fact that we always show up on time.",
            },
            {
                "p1": "Before you buy a new appliance, call {company_name}. We fix refrigerators, washers, ovens, and more across {city} — saving our customers hundreds every time.",
                "p2": "We're the repair team that does it right the first time. Fast, fairly priced, and backed by a guarantee you can count on.",
            },
        ],
        "services": [
            "Refrigerator Repair",
            "Washer & Dryer Repair",
            "Dishwasher Repair",
            "Oven & Range Repair",
            "Microwave Repair",
            "Freezer Repair",
            "Garbage Disposal Repair",
            "Ice Maker Repair",
            "Commercial Appliance Repair",
            "Appliance Installation",
        ],
        "testimonials": [
            {"name": "Randy J.", "stars": 5, "text": "Fixed our refrigerator the same day we called. Saved us from replacing a $2,000 appliance!"},
            {"name": "Diana K.", "stars": 5, "text": "Washer was making a terrible noise. They diagnosed it quickly and had the part the next day."},
            {"name": "Jerry F.", "stars": 5, "text": "Our oven stopped heating right before Thanksgiving. They came out on short notice and saved the holiday!"},
            {"name": "Pamela R.", "stars": 4, "text": "Fair pricing and honest about whether repair or replacement makes more sense. Trustworthy."},
            {"name": "Terry C.", "stars": 5, "text": "Fixed our dishwasher in under an hour. Very knowledgeable and professional technician."},
            {"name": "Joyce L.", "stars": 5, "text": "They've repaired three different appliances for us now. Always reliable and well-priced."},
        ],
    },
    "tree service": {
        "display_name": "Tree Service",
        "icon": "\U0001fab5",
        "primary_color": "from-green-800",
        "secondary_color": "to-emerald-500",
        "accent_color": "green-800",
        "hex_primary": "#166534",
        "hex_dark": "#14532d",
        "hex_light": "#f0fdf4",
        "taglines": [
            "Trees Done Right",
            "Safe Removal. Expert Care.",
            "Healthy Trees. Beautiful Properties.",
            "From Trimming to Takedown — We Handle It",
            "The Tree Experts Your Yard Needs",
            "Protecting Your Property, One Tree at a Time",
        ],
        "subtitles": [
            "Trimming, removal & stump grinding in {city}",
            "Certified arborists serving {city} and beyond",
            "{city}'s trusted team for safe, skilled tree work",
            "Emergency storm cleanup and tree care in {city}",
            "Professional tree services across {city}",
            "Keeping {city} properties safe and beautiful",
        ],
        "about_paragraphs": [
            {
                "p1": "{company_name} provides safe, professional {trade} to homeowners and businesses across {city}. From routine trimming to emergency storm cleanup, our experienced crew handles it all.",
                "p2": "We take the safety of your property seriously — using proper equipment, proven techniques, and thorough cleanup on every job. Your yard will look better than when we arrived.",
            },
            {
                "p1": "Trees are an asset until they become a liability. {company_name} helps {city} property owners maintain healthy trees and safely remove the ones that need to go.",
                "p2": "Our team includes certified arborists who can assess tree health, recommend treatments, and execute complex removals safely. Quality work, fair prices, and a clean site every time.",
            },
            {
                "p1": "{company_name} offers complete {trade} for residential and commercial properties throughout {city}. We trim, prune, remove, and grind stumps — with skill and care.",
                "p2": "Whether it's a single branch or an entire tree, we bring the right crew and equipment to get the job done safely. Licensed, insured, and committed to clean results.",
            },
            {
                "p1": "Storm damage? Overgrown branches? Dead trees? {company_name} tackles it all for {city} homeowners with fast, professional {trade} you can count on.",
                "p2": "We're a locally owned company with deep roots in this community. We care about your property and it shows in the quality of our work.",
            },
        ],
        "services": [
            "Tree Trimming & Pruning",
            "Tree Removal",
            "Stump Grinding & Removal",
            "Emergency Storm Cleanup",
            "Tree Health Assessment",
            "Land Clearing",
            "Hedge Trimming",
            "Tree Planting",
            "Arborist Consultation",
            "Firewood Services",
        ],
        "testimonials": [
            {"name": "Howard G.", "stars": 5, "text": "Removed a massive dead tree that was threatening our house. Skilled crew, zero damage to the yard."},
            {"name": "Kathleen M.", "stars": 5, "text": "The pruning work they did transformed our overgrown trees. Yard gets so much more light now."},
            {"name": "Dale R.", "stars": 5, "text": "Storm brought down a huge limb and they were out the next morning. Fast emergency response."},
            {"name": "Debra W.", "stars": 4, "text": "Stump grinding was quick and clean. You can't even tell there was a tree there anymore."},
            {"name": "Roy S.", "stars": 5, "text": "Their arborist identified a disease in our oak tree and treated it before we lost it. Grateful for the expertise."},
            {"name": "Martha T.", "stars": 5, "text": "Cleared overgrowth on our property line. Professional, safe, and thorough cleanup."},
        ],
    },
    "fencing": {
        "display_name": "Fencing",
        "icon": "\U0001f3d8\ufe0f",
        "primary_color": "from-yellow-700",
        "secondary_color": "to-amber-500",
        "accent_color": "yellow-700",
        "hex_primary": "#a16207",
        "hex_dark": "#854d0e",
        "hex_light": "#fefce8",
        "taglines": [
            "Boundaries Built to Last",
            "Privacy, Security & Curb Appeal",
            "The Fence That Makes the Home",
            "Strong Fences. Trusted Builders.",
            "Your Property, Properly Defined",
            "Built Right. Looks Great. Lasts Longer.",
        ],
        "subtitles": [
            "Wood, vinyl & metal fencing across {city}",
            "Custom fence design and installation in {city}",
            "{city}'s trusted fencing contractors",
            "Privacy, security & decorative fencing in {city}",
            "Fence installation, repair & staining in {city}",
            "Serving {city} with quality fences that last",
        ],
        "about_paragraphs": [
            {
                "p1": "{company_name} builds fences that stand the test of time. We serve {city} homeowners with custom wood, vinyl, chain link, and metal fencing — installed with precision and care.",
                "p2": "From privacy fences to decorative gates, our crew handles every detail from post holes to final staining. We build it right so it lasts for years.",
            },
            {
                "p1": "A great fence adds privacy, security, and curb appeal all at once. {company_name} helps {city} homeowners choose the right fence for their property and budget.",
                "p2": "We handle everything — design consultation, material selection, professional installation, and staining. Our fences look great on day one and hold up for decades.",
            },
            {
                "p1": "{company_name} provides expert {trade} installation and repair throughout {city}. Whether you need a new privacy fence or a gate repair, we do quality work at fair prices.",
                "p2": "Our team calls utility locates, sets proper post depth, and uses quality materials. We take the details seriously because that's what makes a fence last.",
            },
            {
                "p1": "Need a new fence? {company_name} makes it easy for {city} homeowners with free estimates, quality materials, and professional installation you can trust.",
                "p2": "We specialize in wood, vinyl, and metal fencing for residential and commercial properties. Custom designs, clean installs, and a crew that respects your property.",
            },
        ],
        "services": [
            "Wood Fence Installation",
            "Vinyl Fence Installation",
            "Chain Link Fencing",
            "Iron & Metal Fencing",
            "Fence Repair & Restoration",
            "Gate Installation & Repair",
            "Privacy Fence Solutions",
            "Commercial Fencing",
            "Fence Staining & Sealing",
            "Custom Fence Design",
        ],
        "testimonials": [
            {"name": "Craig A.", "stars": 5, "text": "Beautiful cedar privacy fence installed in just two days. Excellent craftsmanship throughout."},
            {"name": "Theresa N.", "stars": 5, "text": "The vinyl fence looks amazing and we'll never have to stain or paint it. Great recommendation."},
            {"name": "Douglas H.", "stars": 5, "text": "Repaired storm damage to our fence quickly and matched the existing style perfectly."},
            {"name": "Beverly C.", "stars": 4, "text": "Professional from estimate to completion. They even called the utility locate service before digging."},
            {"name": "Philip W.", "stars": 5, "text": "Custom gate they built for our driveway is both secure and gorgeous. Gets compliments constantly."},
            {"name": "Joan E.", "stars": 5, "text": "Best fencing company in the area. Fair prices, quality materials, and skilled installers."},
        ],
    },
    "concrete": {
        "display_name": "Concrete",
        "icon": "\U0001f9f1",
        "primary_color": "from-stone-600",
        "secondary_color": "to-gray-400",
        "accent_color": "stone-600",
        "hex_primary": "#57534e",
        "hex_dark": "#44403c",
        "hex_light": "#fafaf9",
        "taglines": [
            "Solid Work. Solid Results.",
            "Concrete That Looks as Good as It Holds",
            "Built on a Foundation of Quality",
            "Flat, Smooth & Made to Last",
            "The Concrete Crew That Gets It Right",
            "Poured with Precision, Built to Endure",
        ],
        "subtitles": [
            "Driveways, patios & foundations across {city}",
            "Stamped, decorative & structural concrete in {city}",
            "{city}'s trusted team for quality concrete work",
            "Residential and commercial concrete in {city}",
            "From slabs to stamped finishes — serving {city}",
            "Expert concrete pouring and repair in {city}",
        ],
        "about_paragraphs": [
            {
                "p1": "{company_name} delivers quality {trade} work across {city} — from driveways and patios to foundations and retaining walls. We pour it right, finish it clean, and build it to last.",
                "p2": "Our experienced crew handles projects of all sizes with the same attention to detail. Proper grading, reinforcement, and finishing techniques that stand up to years of use.",
            },
            {
                "p1": "Concrete is only as good as the crew that pours it. {company_name} brings skilled, experienced workers to every job in {city} — ensuring flat surfaces, clean edges, and lasting results.",
                "p2": "Whether you want a simple slab or a decorative stamped patio, we have the expertise to make it happen. Fair pricing, on-time delivery, and work we stand behind.",
            },
            {
                "p1": "{company_name} provides full-service {trade} for residential and commercial properties throughout {city}. We handle everything from demolition to final sealing.",
                "p2": "Our team takes pride in clean, professional work. We communicate clearly, finish on schedule, and leave your property looking sharp.",
            },
            {
                "p1": "Cracked driveway? Need a new patio? {company_name} handles all types of {trade} work for {city} homeowners — with quality materials and crews that know what they're doing.",
                "p2": "We offer free estimates, transparent pricing, and a commitment to getting the job done right. Concrete you'll be happy with for decades.",
            },
        ],
        "services": [
            "Concrete Driveway Installation",
            "Patio & Sidewalk Pouring",
            "Foundation Repair",
            "Stamped & Decorative Concrete",
            "Concrete Resurfacing",
            "Retaining Wall Construction",
            "Garage Floor Coating",
            "Concrete Removal & Replacement",
            "Commercial Concrete Work",
            "Concrete Sealing & Staining",
        ],
        "testimonials": [
            {"name": "Allen D.", "stars": 5, "text": "New stamped concrete patio looks incredible. Like an upscale outdoor living space now."},
            {"name": "Catherine B.", "stars": 5, "text": "Replaced our cracked driveway and it looks perfect. Smooth finish, clean edges, great work."},
            {"name": "George F.", "stars": 5, "text": "Foundation repair done right. They explained the issue clearly and the fix has held up perfectly."},
            {"name": "Dorothy L.", "stars": 4, "text": "The decorative concrete around our pool turned out beautiful. Transformed the whole backyard."},
            {"name": "Harold P.", "stars": 5, "text": "Poured a new sidewalk and patio for us. Level, smooth, and done on schedule. Very professional."},
            {"name": "Ruth K.", "stars": 5, "text": "Garage floor epoxy coating looks showroom quality. Durable and easy to clean. Love it!"},
        ],
    },
}
