"""Per-trade configuration: services, colors, taglines, testimonials."""

TRADE_CONFIG = {
    "hvac": {
        "display_name": "HVAC",
        "icon": "\u2744\ufe0f",
        "primary_color": "from-blue-600",
        "secondary_color": "to-cyan-500",
        "accent_color": "blue-600",
        "tagline": "Trusted Heating & Cooling Experts in {city}",
        "services": [
            "AC Installation & Replacement",
            "Furnace Repair & Maintenance",
            "Heat Pump Services",
            "Ductwork Installation & Repair",
            "Thermostat Installation",
            "Indoor Air Quality Solutions",
            "Emergency HVAC Repair",
            "Seasonal Tune-Ups",
            "Commercial HVAC Services",
            "Ventilation System Design",
        ],
        "testimonials": [
            {"name": "Mark T.", "stars": 5, "text": "Called them on the hottest day of summer and they had my AC running again within hours. Incredible service!"},
            {"name": "Sarah L.", "stars": 5, "text": "Very professional team. They explained everything clearly and didn't try to upsell me on things I didn't need."},
            {"name": "David R.", "stars": 5, "text": "Our furnace died in January and they came out same day. Fair pricing and quality work. Highly recommend!"},
            {"name": "Jennifer K.", "stars": 4, "text": "Great annual maintenance service. Our system runs more efficiently now and our energy bills dropped noticeably."},
            {"name": "Robert M.", "stars": 5, "text": "Installed a new heat pump for us. The crew was clean, punctual, and the install was flawless."},
            {"name": "Lisa W.", "stars": 5, "text": "Best HVAC company in the area. They've serviced our home for three years and never disappoint."},
        ],
    },
    "plumbing": {
        "display_name": "Plumbing",
        "icon": "\U0001f6bf",
        "primary_color": "from-sky-600",
        "secondary_color": "to-blue-400",
        "accent_color": "sky-600",
        "tagline": "Reliable Plumbing Services in {city}",
        "services": [
            "Drain Cleaning & Unclogging",
            "Water Heater Installation & Repair",
            "Pipe Repair & Replacement",
            "Sewer Line Services",
            "Fixture Installation",
            "Leak Detection & Repair",
            "Garbage Disposal Services",
            "Emergency Plumbing",
            "Water Softener Installation",
            "Bathroom & Kitchen Remodel Plumbing",
        ],
        "testimonials": [
            {"name": "Chris B.", "stars": 5, "text": "Fixed a major leak under our kitchen sink in no time. Very knowledgeable and left everything spotless."},
            {"name": "Amanda S.", "stars": 5, "text": "They replaced our old water heater and the difference is amazing. Hot water on demand now!"},
            {"name": "Tom H.", "stars": 5, "text": "Had a clogged drain that two other companies couldn't fix. These guys solved it on the first visit."},
            {"name": "Rachel P.", "stars": 4, "text": "Professional, on time, and reasonably priced. They're now our go-to plumber for everything."},
            {"name": "Steve G.", "stars": 5, "text": "Emergency call at 11pm and they were at our door within 30 minutes. Saved us from a flooded basement."},
            {"name": "Nicole D.", "stars": 5, "text": "Honest and dependable. They gave us options and helped us choose what fit our budget."},
        ],
    },
    "electrical": {
        "display_name": "Electrical",
        "icon": "\u26a1",
        "primary_color": "from-amber-500",
        "secondary_color": "to-yellow-400",
        "accent_color": "amber-500",
        "tagline": "Licensed Electricians Serving {city}",
        "services": [
            "Electrical Panel Upgrades",
            "Outlet & Switch Installation",
            "Lighting Installation & Design",
            "Ceiling Fan Installation",
            "Whole-Home Rewiring",
            "EV Charger Installation",
            "Generator Installation",
            "Smoke & CO Detector Installation",
            "Surge Protection",
            "Commercial Electrical Services",
        ],
        "testimonials": [
            {"name": "Brian F.", "stars": 5, "text": "Upgraded our entire panel to handle modern loads. Work was clean and passed inspection with flying colors."},
            {"name": "Karen J.", "stars": 5, "text": "Installed recessed lighting throughout our home. It looks absolutely amazing and was done in one day."},
            {"name": "Mike C.", "stars": 5, "text": "Very safety-conscious team. They found and fixed wiring issues the previous owners left behind."},
            {"name": "Donna A.", "stars": 4, "text": "Quick and professional EV charger installation. Now we charge at home every night hassle-free."},
            {"name": "Greg W.", "stars": 5, "text": "They rewired our 1960s home and brought everything up to code. Couldn't be happier with the results."},
            {"name": "Patricia N.", "stars": 5, "text": "Always responsive and fair with pricing. We've used them for multiple projects now."},
        ],
    },
    "lawn care": {
        "display_name": "Lawn Care",
        "icon": "\U0001f33f",
        "primary_color": "from-green-600",
        "secondary_color": "to-lime-500",
        "accent_color": "green-600",
        "tagline": "Professional Lawn Care in {city}",
        "services": [
            "Weekly Lawn Mowing",
            "Lawn Fertilization Programs",
            "Weed Control & Treatment",
            "Aeration & Overseeding",
            "Spring & Fall Cleanup",
            "Edging & Trimming",
            "Sod Installation",
            "Lawn Disease Treatment",
            "Irrigation System Maintenance",
            "Organic Lawn Care",
        ],
        "testimonials": [
            {"name": "Paul E.", "stars": 5, "text": "My lawn has never looked this good. The neighbors keep asking who my lawn guy is!"},
            {"name": "Susan M.", "stars": 5, "text": "Reliable, consistent, and my yard looks like a golf course. Best decision I've made for my home."},
            {"name": "Dan K.", "stars": 5, "text": "They revived my brown, patchy lawn into something beautiful. Great fertilization program."},
            {"name": "Mary L.", "stars": 4, "text": "Always on time and do a thorough job. They even blow off the driveway and sidewalks after mowing."},
            {"name": "Jeff R.", "stars": 5, "text": "The aeration and overseeding service made a huge difference. Thick, green lawn all season long."},
            {"name": "Cindy T.", "stars": 5, "text": "Affordable and professional. They customized a plan for my yard's specific needs."},
        ],
    },
    "landscaping": {
        "display_name": "Landscaping",
        "icon": "\U0001f333",
        "primary_color": "from-emerald-600",
        "secondary_color": "to-green-400",
        "accent_color": "emerald-600",
        "tagline": "Beautiful Landscaping Design & Installation in {city}",
        "services": [
            "Landscape Design & Planning",
            "Hardscape Installation",
            "Patio & Walkway Construction",
            "Retaining Wall Building",
            "Garden Bed Installation",
            "Outdoor Lighting",
            "Water Feature Installation",
            "Xeriscaping & Drought-Tolerant Design",
            "Mulch & Rock Installation",
            "Seasonal Planting",
        ],
        "testimonials": [
            {"name": "Andrew B.", "stars": 5, "text": "They transformed our backyard into an oasis. The patio and garden design exceeded our expectations."},
            {"name": "Michelle G.", "stars": 5, "text": "Creative designers who really listen. Our front yard went from embarrassing to the best on the block."},
            {"name": "Kevin D.", "stars": 5, "text": "The retaining wall they built is both functional and beautiful. Great craftsmanship throughout."},
            {"name": "Laura S.", "stars": 4, "text": "Excellent xeriscaping work that cut our water bill in half. Looks gorgeous year-round."},
            {"name": "Ryan P.", "stars": 5, "text": "Professional crew, on budget, and finished ahead of schedule. Our outdoor space is now our favorite room."},
            {"name": "Heather W.", "stars": 5, "text": "From design to final install, everything was seamless. We get compliments from everyone who visits."},
        ],
    },
    "roofing": {
        "display_name": "Roofing",
        "icon": "\U0001f3e0",
        "primary_color": "from-red-700",
        "secondary_color": "to-orange-500",
        "accent_color": "red-700",
        "tagline": "Expert Roofing Contractors in {city}",
        "services": [
            "Roof Replacement",
            "Roof Repair & Patching",
            "Shingle Installation",
            "Metal Roofing",
            "Flat Roof Services",
            "Roof Inspection & Assessment",
            "Storm Damage Repair",
            "Gutter Installation & Repair",
            "Skylight Installation",
            "Commercial Roofing",
        ],
        "testimonials": [
            {"name": "James H.", "stars": 5, "text": "Replaced our entire roof in two days. Clean, efficient, and the new roof looks fantastic."},
            {"name": "Barbara C.", "stars": 5, "text": "They found and fixed a leak that had been causing damage for months. Thorough and professional."},
            {"name": "William F.", "stars": 5, "text": "Handled our insurance claim for storm damage seamlessly. Made a stressful situation easy."},
            {"name": "Linda M.", "stars": 4, "text": "Great quality materials and workmanship. Our metal roof should last a lifetime."},
            {"name": "Charles R.", "stars": 5, "text": "Fair estimate, no surprises, and excellent cleanup. You'd never know they were here except for the beautiful new roof."},
            {"name": "Elizabeth A.", "stars": 5, "text": "The best roofing company we've ever worked with. Responsive, honest, and skilled."},
        ],
    },
    "painting": {
        "display_name": "Painting",
        "icon": "\U0001f3a8",
        "primary_color": "from-violet-600",
        "secondary_color": "to-purple-400",
        "accent_color": "violet-600",
        "tagline": "Professional Painting Services in {city}",
        "services": [
            "Interior Painting",
            "Exterior Painting",
            "Cabinet Painting & Refinishing",
            "Deck & Fence Staining",
            "Drywall Repair & Texturing",
            "Color Consultation",
            "Wallpaper Removal",
            "Pressure Washing",
            "Commercial Painting",
            "Epoxy Floor Coating",
        ],
        "testimonials": [
            {"name": "Scott B.", "stars": 5, "text": "Painted our entire interior in three days. Clean lines, no drips, and beautiful color matching."},
            {"name": "Angela T.", "stars": 5, "text": "The exterior paint job made our house look brand new. Neighbors think we renovated!"},
            {"name": "Jason K.", "stars": 5, "text": "Their cabinet refinishing saved us thousands over replacement. Kitchen looks completely transformed."},
            {"name": "Diane L.", "stars": 4, "text": "Great attention to detail. They properly prepped every surface and it shows in the final result."},
            {"name": "Timothy M.", "stars": 5, "text": "Professional crew that respects your home. Drop cloths everywhere, furniture moved carefully, spotless cleanup."},
            {"name": "Carolyn R.", "stars": 5, "text": "The color consultation was so helpful. They guided us to the perfect palette for our space."},
        ],
    },
    "pest control": {
        "display_name": "Pest Control",
        "icon": "\U0001f41c",
        "primary_color": "from-teal-600",
        "secondary_color": "to-green-500",
        "accent_color": "teal-600",
        "tagline": "Effective Pest Control Solutions in {city}",
        "services": [
            "General Pest Treatment",
            "Ant & Spider Control",
            "Rodent Removal & Exclusion",
            "Termite Inspection & Treatment",
            "Mosquito Control",
            "Wasp & Bee Removal",
            "Bed Bug Treatment",
            "Wildlife Removal",
            "Recurring Prevention Plans",
            "Commercial Pest Management",
        ],
        "testimonials": [
            {"name": "Nathan R.", "stars": 5, "text": "Got rid of our ant problem completely after one treatment. No more bugs in the kitchen!"},
            {"name": "Kelly S.", "stars": 5, "text": "Their quarterly plan keeps our home pest-free year-round. Haven't seen a spider in months."},
            {"name": "Anthony J.", "stars": 5, "text": "Professional rodent exclusion service. They sealed every entry point and the mice are gone for good."},
            {"name": "Deborah H.", "stars": 4, "text": "Thorough termite inspection and treatment. They explained everything and put our minds at ease."},
            {"name": "Frank P.", "stars": 5, "text": "Safe treatments that are effective but gentle around our kids and pets. Very impressed."},
            {"name": "Marie G.", "stars": 5, "text": "Fast response time and the technician was incredibly knowledgeable. Problem solved on the first visit."},
        ],
    },
    "carpet cleaning": {
        "display_name": "Carpet Cleaning",
        "icon": "\u2728",
        "primary_color": "from-indigo-600",
        "secondary_color": "to-blue-400",
        "accent_color": "indigo-600",
        "tagline": "Professional Carpet & Upholstery Cleaning in {city}",
        "services": [
            "Deep Steam Carpet Cleaning",
            "Stain Removal Treatment",
            "Pet Odor & Stain Removal",
            "Upholstery Cleaning",
            "Tile & Grout Cleaning",
            "Area Rug Cleaning",
            "Commercial Carpet Cleaning",
            "Carpet Repair & Stretching",
            "Scotchgard Protection",
            "Move-In/Move-Out Cleaning",
        ],
        "testimonials": [
            {"name": "Travis D.", "stars": 5, "text": "Our carpets look brand new! They got out stains I thought were permanent. Amazing results."},
            {"name": "Megan F.", "stars": 5, "text": "Pet stain and odor completely gone. We can finally have guests over without embarrassment."},
            {"name": "Russell B.", "stars": 5, "text": "Used them for our move-out cleaning and got our full deposit back. Worth every penny."},
            {"name": "Amy C.", "stars": 4, "text": "Quick drying time and the carpets feel so soft and fresh. Will definitely use again."},
            {"name": "Donald W.", "stars": 5, "text": "They cleaned our upholstery too and the whole living room looks and smells incredible."},
            {"name": "Sharon J.", "stars": 5, "text": "Very professional service. They moved furniture carefully and put everything back perfectly."},
        ],
    },
    "handyman": {
        "display_name": "Handyman",
        "icon": "\U0001f527",
        "primary_color": "from-orange-600",
        "secondary_color": "to-amber-400",
        "accent_color": "orange-600",
        "tagline": "Your Trusted Handyman in {city}",
        "services": [
            "General Home Repairs",
            "Furniture Assembly",
            "Drywall Patching & Repair",
            "Door & Window Repairs",
            "Shelving & Mounting",
            "Minor Plumbing Fixes",
            "Minor Electrical Work",
            "Caulking & Weatherproofing",
            "Deck & Fence Repair",
            "Honey-Do Lists",
        ],
        "testimonials": [
            {"name": "Roger K.", "stars": 5, "text": "Knocked out my entire honey-do list in one afternoon. My wife is thrilled!"},
            {"name": "Tammy L.", "stars": 5, "text": "Fixed a dozen little things around the house that had been bugging me for months. Great service."},
            {"name": "Carl M.", "stars": 5, "text": "Mounted our TV, assembled furniture, and fixed a leaky faucet all in one visit. Super efficient."},
            {"name": "Janet E.", "stars": 4, "text": "Reliable, skilled, and reasonably priced. They're my first call for any home repair now."},
            {"name": "Dennis R.", "stars": 5, "text": "Fixed drywall damage from a door handle and you can't even tell it was ever there. Impressive work."},
            {"name": "Brenda S.", "stars": 5, "text": "So nice to have one person who can handle all the little repairs. Saves time and money."},
        ],
    },
    "garage door repair": {
        "display_name": "Garage Door Repair",
        "icon": "\U0001f6aa",
        "primary_color": "from-gray-700",
        "secondary_color": "to-slate-500",
        "accent_color": "gray-700",
        "tagline": "Expert Garage Door Repair & Installation in {city}",
        "services": [
            "Garage Door Repair",
            "Garage Door Installation",
            "Spring Replacement",
            "Opener Repair & Installation",
            "Panel Replacement",
            "Track Alignment & Repair",
            "Weather Seal Replacement",
            "Safety Sensor Adjustment",
            "Smart Opener Upgrades",
            "Emergency Garage Door Service",
        ],
        "testimonials": [
            {"name": "Larry H.", "stars": 5, "text": "Broken spring at 7am and they had it fixed by noon. Fast, professional, and fair priced."},
            {"name": "Sandra P.", "stars": 5, "text": "Installed a beautiful new garage door that completely changed our home's curb appeal."},
            {"name": "Wayne T.", "stars": 5, "text": "Our door was off-track and they diagnosed and fixed it quickly. Runs smooth as butter now."},
            {"name": "Gloria B.", "stars": 4, "text": "Upgraded our opener to a smart one. Love being able to check if the garage is closed from my phone."},
            {"name": "Keith D.", "stars": 5, "text": "Honest assessment — they repaired what needed fixing instead of pushing a full replacement. Respect."},
            {"name": "Betty M.", "stars": 5, "text": "They service our garage doors annually. Quiet, smooth operation every time. Great preventive maintenance."},
        ],
    },
    "appliance repair": {
        "display_name": "Appliance Repair",
        "icon": "\U0001f9f0",
        "primary_color": "from-slate-600",
        "secondary_color": "to-gray-400",
        "accent_color": "slate-600",
        "tagline": "Fast & Reliable Appliance Repair in {city}",
        "services": [
            "Refrigerator Repair",
            "Washer & Dryer Repair",
            "Dishwasher Repair",
            "Oven & Range Repair",
            "Microwave Repair",
            "Freezer Repair",
            "Garbage Disposal Repair",
            "Ice Maker Repair",
            "Commercial Appliance Repair",
            "Appliance Installation",
        ],
        "testimonials": [
            {"name": "Randy J.", "stars": 5, "text": "Fixed our refrigerator the same day we called. Saved us from replacing a $2,000 appliance!"},
            {"name": "Diana K.", "stars": 5, "text": "Washer was making a terrible noise. They diagnosed it quickly and had the part the next day."},
            {"name": "Jerry F.", "stars": 5, "text": "Our oven stopped heating right before Thanksgiving. They came out on short notice and saved the holiday!"},
            {"name": "Pamela R.", "stars": 4, "text": "Fair pricing and honest about whether repair or replacement makes more sense. Trustworthy."},
            {"name": "Terry C.", "stars": 5, "text": "Fixed our dishwasher in under an hour. Very knowledgeable and professional technician."},
            {"name": "Joyce L.", "stars": 5, "text": "They've repaired three different appliances for us now. Always reliable and well-priced."},
        ],
    },
    "tree service": {
        "display_name": "Tree Service",
        "icon": "\U0001fab5",
        "primary_color": "from-green-800",
        "secondary_color": "to-emerald-500",
        "accent_color": "green-800",
        "tagline": "Professional Tree Care & Removal in {city}",
        "services": [
            "Tree Trimming & Pruning",
            "Tree Removal",
            "Stump Grinding & Removal",
            "Emergency Storm Cleanup",
            "Tree Health Assessment",
            "Land Clearing",
            "Hedge Trimming",
            "Tree Planting",
            "Arborist Consultation",
            "Firewood Services",
        ],
        "testimonials": [
            {"name": "Howard G.", "stars": 5, "text": "Removed a massive dead tree that was threatening our house. Skilled crew, zero damage to the yard."},
            {"name": "Kathleen M.", "stars": 5, "text": "The pruning work they did transformed our overgrown trees. Yard gets so much more light now."},
            {"name": "Dale R.", "stars": 5, "text": "Storm brought down a huge limb and they were out the next morning. Fast emergency response."},
            {"name": "Debra W.", "stars": 4, "text": "Stump grinding was quick and clean. You can't even tell there was a tree there anymore."},
            {"name": "Roy S.", "stars": 5, "text": "Their arborist identified a disease in our oak tree and treated it before we lost it. Grateful for the expertise."},
            {"name": "Martha T.", "stars": 5, "text": "Cleared overgrowth on our property line. Professional, safe, and thorough cleanup."},
        ],
    },
    "fencing": {
        "display_name": "Fencing",
        "icon": "\U0001f3d8\ufe0f",
        "primary_color": "from-yellow-700",
        "secondary_color": "to-amber-500",
        "accent_color": "yellow-700",
        "tagline": "Quality Fence Installation & Repair in {city}",
        "services": [
            "Wood Fence Installation",
            "Vinyl Fence Installation",
            "Chain Link Fencing",
            "Iron & Metal Fencing",
            "Fence Repair & Restoration",
            "Gate Installation & Repair",
            "Privacy Fence Solutions",
            "Commercial Fencing",
            "Fence Staining & Sealing",
            "Custom Fence Design",
        ],
        "testimonials": [
            {"name": "Craig A.", "stars": 5, "text": "Beautiful cedar privacy fence installed in just two days. Excellent craftsmanship throughout."},
            {"name": "Theresa N.", "stars": 5, "text": "The vinyl fence looks amazing and we'll never have to stain or paint it. Great recommendation."},
            {"name": "Douglas H.", "stars": 5, "text": "Repaired storm damage to our fence quickly and matched the existing style perfectly."},
            {"name": "Beverly C.", "stars": 4, "text": "Professional from estimate to completion. They even called the utility locate service before digging."},
            {"name": "Philip W.", "stars": 5, "text": "Custom gate they built for our driveway is both secure and gorgeous. Gets compliments constantly."},
            {"name": "Joan E.", "stars": 5, "text": "Best fencing company in the area. Fair prices, quality materials, and skilled installers."},
        ],
    },
    "concrete": {
        "display_name": "Concrete",
        "icon": "\U0001f9f1",
        "primary_color": "from-stone-600",
        "secondary_color": "to-gray-400",
        "accent_color": "stone-600",
        "tagline": "Expert Concrete Services in {city}",
        "services": [
            "Concrete Driveway Installation",
            "Patio & Sidewalk Pouring",
            "Foundation Repair",
            "Stamped & Decorative Concrete",
            "Concrete Resurfacing",
            "Retaining Wall Construction",
            "Garage Floor Coating",
            "Concrete Removal & Replacement",
            "Commercial Concrete Work",
            "Concrete Sealing & Staining",
        ],
        "testimonials": [
            {"name": "Allen D.", "stars": 5, "text": "New stamped concrete patio looks incredible. Like an upscale outdoor living space now."},
            {"name": "Catherine B.", "stars": 5, "text": "Replaced our cracked driveway and it looks perfect. Smooth finish, clean edges, great work."},
            {"name": "George F.", "stars": 5, "text": "Foundation repair done right. They explained the issue clearly and the fix has held up perfectly."},
            {"name": "Dorothy L.", "stars": 4, "text": "The decorative concrete around our pool turned out beautiful. Transformed the whole backyard."},
            {"name": "Harold P.", "stars": 5, "text": "Poured a new sidewalk and patio for us. Level, smooth, and done on schedule. Very professional."},
            {"name": "Ruth K.", "stars": 5, "text": "Garage floor epoxy coating looks showroom quality. Durable and easy to clean. Love it!"},
        ],
    },
}
